config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :light_supplies do
    resources :invoices, shallow: true
  end
  resources :gas_supplies do
    resources :invoices, shallow: true
  end
  resources :water_supplies do
    resources :invoices, shallow: true
  end
end

app/models/water_supply.rb
class WaterSupply < ApplicationRecord
  include Billable
  belongs_to :house
end

app/controllers/water_supplies_controller.rb
class WaterSuppliesController < ApplicationController
  before_action :set_water_supply, only: [:show, :edit, :update, :destroy]

  # GET /water_supplies
  def index
    @water_supplies = WaterSupply.all
  end

  # GET /water_supplies/1
  def show
  end

  # GET /water_supplies/new
  def new
    @water_supply = WaterSupply.new
  end

  # GET /water_supplies/1/edit
  def edit
  end

  # POST /water_supplies
  def create
    @water_supply = WaterSupply.new(water_supply_params)

    respond_to do |format|
      if @water_supply.save
        format.html { redirect_to @water_supply, notice: 'Water supply was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /water_supplies/1
  # PATCH/PUT /water_supplies/1.json
  def update
    respond_to do |format|
      if @water_supply.update(water_supply_params)
        format.html { redirect_to @water_supply, notice: 'Water supply was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /water_supplies/1
  # DELETE /water_supplies/1.json
  def destroy
    @water_supply.destroy
    respond_to do |format|
      format.html { redirect_to water_supplies_url, notice: 'Water supply was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water_supply
      @water_supply = WaterSupply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def water_supply_params
      params.require(:water_supply).permit(:provider, :house_id)
    end
end

app/helpers/water_supplies_helper.rb
module WaterSuppliesHelper
end

app/views/water_supplies/_form.html.erb
<%= form_with(model: water_supply, local: true) do |form| %>
  <% if water_supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(water_supply.errors.count, "error") %> prohibited this water_supply from being saved:</h2>

      <ul>
      <% water_supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="field">
    <%= form.label :house_id %>
    <%= form.collection_select(:house_id, House.all, :id, :address) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/water_supplies/edit.html.erb
<h1>Editing Water Supply</h1>

<%= render 'form', water_supply: @water_supply %>

<%= link_to 'Show', @water_supply %> |
<%= link_to 'Back', water_supplies_path %>

app/views/water_supplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Water Supplies</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>House</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @water_supplies.each do |water_supply| %>
      <tr>
        <td><%= water_supply.provider %></td>
        <td><%= water_supply.house.address %></td>
        <td><%= link_to 'Show', water_supply %></td>
        <td><%= link_to 'Edit', edit_water_supply_path(water_supply) %></td>
        <td><%= link_to 'Destroy', water_supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Water Supply', new_water_supply_path %>
<%= link_to 'Houses', houses_path %>

app/views/water_supplies/new.html.erb
<h1>New Water Supply</h1>

<%= render 'form', water_supply: @water_supply %>

<%= link_to 'Back', water_supplies_path %>

app/views/water_supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @water_supply.provider %>
</p>

<p>
  <strong>House:</strong>
  <%= @water_supply.house.address %>
</p>

<%= link_to 'Edit', edit_water_supply_path(@water_supply) %> |
<%= link_to 'Back', house_path(@water_supply.house) %>