config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :light_supplies do
    resources :invoices, shallow: true
  end
  resources :gas_supplies do
    resources :invoices, shallow: true
  end
  resources :water_supplies do
    resources :invoices, shallow: true
  end
end

app/models/light_supply.rb
class LightSupply < ApplicationRecord
  include Billable
  belongs_to :house
end

app/controllers/light_supplies_controller.rb
class LightSuppliesController < ApplicationController
  before_action :set_light_supply, only: [:show, :edit, :update, :destroy]

  # GET /light_supplies
  def index
    @light_supplies = LightSupply.all
  end

  # GET /light_supplies/1
  def show
  end

  # GET /light_supplies/new
  def new
    @light_supply = LightSupply.new
  end

  # GET /light_supplies/1/edit
  def edit
  end

  # POST /light_supplies
  def create
    @light_supply = LightSupply.new(light_supply_params)

    respond_to do |format|
      if @light_supply.save
        format.html { redirect_to @light_supply, notice: 'Light supply was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /light_supplies/1
  # PATCH/PUT /light_supplies/1.json
  def update
    respond_to do |format|
      if @light_supply.update(light_supply_params)
        format.html { redirect_to @light_supply, notice: 'Light supply was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /light_supplies/1
  # DELETE /light_supplies/1.json
  def destroy
    @light_supply.destroy
    respond_to do |format|
      format.html { redirect_to light_supplies_url, notice: 'Light supply was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_light_supply
      @light_supply = LightSupply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def light_supply_params
      params.require(:light_supply).permit(:provider, :house_id)
    end
end

app/helpers/light_supplies_helper.rb
module LightSuppliesHelper
end

app/views/light_supplies/_form.html.erb
<%= form_with(model: light_supply, local: true) do |form| %>
  <% if light_supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(light_supply.errors.count, "error") %> prohibited this light_supply from being saved:</h2>

      <ul>
      <% light_supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="field">
    <%= form.label :house_id %>
    <%= form.collection_select(:house_id, House.all, :id, :address) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/light_supplies/edit.html.erb
<h1>Editing Light Supply</h1>

<%= render 'form', light_supply: @light_supply %>

<%= link_to 'Show', @light_supply %> |
<%= link_to 'Back', light_supplies_path %>

app/views/light_supplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Light Supplies</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>House</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @light_supplies.each do |light_supply| %>
      <tr>
        <td><%= light_supply.provider %></td>
        <td><%= light_supply.house.address %></td>
        <td><%= link_to 'Show', light_supply %></td>
        <td><%= link_to 'Edit', edit_light_supply_path(light_supply) %></td>
        <td><%= link_to 'Destroy', light_supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Light Supply', new_light_supply_path %>
<%= link_to 'Houses', houses_path %>

app/views/light_supplies/new.html.erb
<h1>New Light Supply</h1>

<%= render 'form', light_supply: @light_supply %>

<%= link_to 'Back', light_supplies_path %>

app/views/light_supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @light_supply.provider %>
</p>

<p>
  <strong>House:</strong>
  <%= @light_supply.house.address %>
</p>

<%= link_to 'Edit', edit_light_supply_path(@light_supply) %> |
<%= link_to 'Back', house_path(@light_supply.house) %>