config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :light_supplies do
    resources :invoices, shallow: true
  end
  resources :gas_supplies do
    resources :invoices, shallow: true
  end
  resources :water_supplies do
    resources :invoices, shallow: true
  end
end

app/models/gas_supply.rb
class GasSupply < ApplicationRecord
  include Billable
  belongs_to :house
end

app/controllers/gas_supplies_controller.rb
class GasSuppliesController < ApplicationController
  before_action :set_gas_supply, only: [:show, :edit, :update, :destroy]

  # GET /gas_supplies
  def index
    @gas_supplies = GasSupply.all
  end

  # GET /gas_supplies/1
  def show
  end

  # GET /gas_supplies/new
  def new
    @gas_supply = GasSupply.new
  end

  # GET /gas_supplies/1/edit
  def edit
  end

  # POST /gas_supplies
  def create
    @gas_supply = GasSupply.new(gas_supply_params)

    respond_to do |format|
      if @gas_supply.save
        format.html { redirect_to @gas_supply, notice: 'Gas supply was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /gas_supplies/1
  def update
    respond_to do |format|
      if @gas_supply.update(gas_supply_params)
        format.html { redirect_to @gas_supply, notice: 'Gas supply was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /gas_supplies/1
  def destroy
    @gas_supply.destroy
    respond_to do |format|
      format.html { redirect_to gas_supplies_url, notice: 'Gas supply was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gas_supply
      @gas_supply = GasSupply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gas_supply_params
      params.require(:gas_supply).permit(:provider, :house_id)
    end
end

app/helpers/gas_supplies_helper.rb
module GasSuppliesHelper
end

app/views/gas_supplies/_form.html.erb
<%= form_with(model: gas_supply, local: true) do |form| %>
  <% if gas_supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gas_supply.errors.count, "error") %> prohibited this gas_supply from being saved:</h2>

      <ul>
      <% gas_supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="field">
    <%= form.label :house_id %>
    <%= form.collection_select(:house_id, House.all, :id, :address) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gas_supplies/edit.html.erb
<h1>Editing Gas Supply</h1>

<%= render 'form', gas_supply: @gas_supply %>

<%= link_to 'Show', @gas_supply %> |
<%= link_to 'Back', gas_supplies_path %>

app/views/gas_supplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gas Supplies</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>House</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gas_supplies.each do |gas_supply| %>
      <tr>
        <td><%= gas_supply.provider %></td>
        <td><%= gas_supply.house.address %></td>
        <td><%= link_to 'Show', gas_supply %></td>
        <td><%= link_to 'Edit', edit_gas_supply_path(gas_supply) %></td>
        <td><%= link_to 'Destroy', gas_supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gas Supply', new_gas_supply_path %> <br>
<%= link_to 'Houses', houses_path %>

app/views/gas_supplies/new.html.erb
<h1>New Gas Supply</h1>

<%= render 'form', gas_supply: @gas_supply %>

<%= link_to 'Back', gas_supplies_path %>

app/views/gas_supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @gas_supply.provider %>
</p>

<p>
  <strong>House:</strong>
  <%= @gas_supply.house.address %>
</p>

<p>
  <% if @gas_supply.invoices.any? %>
    <%= link_to 'Invoices', gas_supply_invoices_path(@gas_supply) %>
  <% else %>
    <%= link_to 'Add invoice', new_gas_supply_invoice_path(@gas_supply) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_gas_supply_path(@gas_supply) %> |
<%= link_to 'Back', house_path(@gas_supply.house) %>